version: "3.8"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: cs348_project
      MYSQL_USER: group8
      MYSQL_PASSWORD: Password0!
      MYSQL_ROOT_PASSWORD: Password0!
    ports:
      - "3306:3306"
    volumes:
      - "./data:/var/lib/mysql"
    healthcheck:
      test: "mysql $$MYSQL_DATABASE -u$$MYSQL_USER -p$$MYSQL_PASSWORD -e 'SELECT 1;'"
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  api:
    build:
      context: ./api/
    ports:
      - "6608:6608"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "./api:/app"
