"""empty message

Revision ID: 473d3a3a2dca
Revises: e7dc09a50f96
Create Date: 2023-06-05 15:02:41.117155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473d3a3a2dca'
down_revision = 'e7dc09a50f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurant',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('restaurant_id', sa.INTEGER(), nullable=False),
    sa.Column('calories', sa.INTEGER(), nullable=True),
    sa.Column('fat', sa.INTEGER(), nullable=True),
    sa.Column('carb', sa.INTEGER(), nullable=True),
    sa.Column('fiber', sa.INTEGER(), nullable=True),
    sa.Column('protein', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_item')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
