"""Create food_item and restaurant tables

Revision ID: e7dc09a50f96
Revises: 
Create Date: 2023-06-04 13:53:52.384427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7dc09a50f96'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('restaurant',
                    sa.Column('id', mysql.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', mysql.VARCHAR(
                        length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )
    op.create_table('food_item',
                    sa.Column('id', mysql.INTEGER(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', mysql.VARCHAR(
                        length=255), nullable=True),
                    sa.Column('restaurant_id', mysql.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('calories', mysql.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('fat', mysql.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('carb', mysql.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('fiber', mysql.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.Column('protein', mysql.INTEGER(),
                              autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(
                        ['restaurant_id'], ['restaurant.id'], name='food_item_ibfk_1'),
                    sa.PrimaryKeyConstraint('id'),
                    mysql_collate='utf8mb4_0900_ai_ci',
                    mysql_default_charset='utf8mb4',
                    mysql_engine='InnoDB'
                    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_item')
    op.drop_table('restaurant')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
