"""empty message

Revision ID: 95c5f0d415b5
Revises: f2b5ccc7da96
Create Date: 2023-06-21 12:01:08.465253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c5f0d415b5'
down_revision = 'f2b5ccc7da96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('goal_type', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.Column('streak', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal')
    # ### end Alembic commands ###
